### ISSUE TITLE
To Do list element (local storage for data)

### ISSUE THREAD

**Issue by ssarahs-lab** [chingu-voyages/v9-toucans-team-05#8]

**Comment by peppertaro** [comment]
Tested on branch and merged to master. also confirmed it works properly on master.

**Comment by peppertaro** [comment]
Merged & tested on local / heroku link.
As unsplash API has access limit (for demo version it is 50 times/hour[so far we are on this grade] and I already requested production version which is 5000 times/hour), I set source unsplash to escape (for now if we have access over 50 times / hour, it loads @sarebear her collection)
