### ISSUE TITLE
Search bar - Bing/Google/Duckduckgo

### ISSUE THREAD

**Issue by ssarahs-lab** [chingu-voyages/v9-toucans-team-05#9]

**Comment by JH1408** [comment]
If I click on the arrow next to the bing symbol nothing happens. Are you aware of that? :)

**Comment by peppertaro** [comment]
I have updated to an arrow and it works when it clicks , too.

**Comment by peppertaro** [comment]
I merged this branch and confirmed it works properly, so I close this branch.

**Comment by peppertaro** [comment]
Updated searchbar font to show it in #fff.

**Comment by peppertaro** [comment]
merged to master and confirmed it works.

**Comment by peppertaro** [comment]
I'm gonna close this as this is merged.
